import Head from 'next/head'
import Image from 'next/image'
import Sound from "../components/sound/Sound.js";
import Player from "../components/player/Player.js";
import { useSelector } from 'react-redux';
import tracks from '../data/tracks.json';
export default function Home({allTracks}) {
  const track = useSelector((state)=> state.trackPlayer.track);
  return (
    <div>
      <Head>
        <title>Sound Track</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>
      <Sound tracks={allTracks}/>
      {track.toString().trim() !== ""?   <Player/>:""}
    </div>
  )
}

export async function getStaticProps(){
  console.log(tracks)
   return {
      props:{
        allTracks:tracks
      }
   }
}